name: ci-helm-ghcr
permissions:
  packages: write
  contents: read
on:
  workflow_dispatch:
  push:
    branches: [ "*" ]
env:
  CHART_NAME: hello
  IMAGE_TAG: -${{ github.ref_name}}+${{ github.sha }}
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: helm lint
        run: |
          helm lint charts
      - name: helm login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u $ --password-stdin
      - name: helm package
        run: |
          helm package charts --version $IMAGE_TAG
      - name: helm push
        run: |
          helm push $CHART_NAME-$IMAGE_TAG.tgz oci://ghcr.io/${{ github.repository }}
